# Generated by Django 2.2.7 on 2020-04-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1024)),
                ('affected', models.CharField(max_length=5)),
                ('fix', models.CharField(max_length=5)),
                ('colour', models.CharField(max_length=10)),
                ('priority', models.CharField(max_length=10)),
                ('attachments', models.ManyToManyField(related_name='issue_attachments', to='attachment.Attachment')),
            ],
        ),
    ]
