# Generated by Django 2.2.7 on 2020-04-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_account', models.CharField(max_length=120)),
                ('git_token', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
