# Generated by Django 2.2.7 on 2020-04-18 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
                ('issues', models.ManyToManyField(related_name='project_issues', to='issue.Issue')),
                ('members', models.ManyToManyField(related_name='project_members', to='profile.Profile')),
            ],
        ),
    ]
