# Generated by Django 3.0 on 2020-02-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Issue', '0001_initial'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=1024)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
                ('issues', models.ManyToManyField(related_name='project_issues', to='Issue.Issue')),
                ('members', models.ManyToManyField(related_name='project_members', to='Profile.Profile')),
            ],
        ),
    ]
